#!/bin/bash
# =============================================================================
# PostgreSQL Network Access Configuration
# =============================================================================
# This script runs at PostgreSQL startup and configures pg_hba.conf to allow
# connections from:
#   - Docker bridge networks (172.16.0.0/12, 10.0.0.0/8)
#   - Host network (for rootless Docker containers connecting via host IP)
#   - Localhost
#
# This is necessary because rootless Docker containers cannot access localhost
# and must connect via the host's IP address.
# =============================================================================

set -e

# Configuration file path
PG_HBA_FILE="$PGDATA/pg_hba.conf"

echo "Configuring PostgreSQL network access for SUJBOT..."

# Wait for pg_hba.conf to be created by postgres init
if [ ! -f "$PG_HBA_FILE" ]; then
    echo "Waiting for pg_hba.conf to be created..."
    sleep 2
fi

# Backup original
if [ -f "$PG_HBA_FILE" ]; then
    cp "$PG_HBA_FILE" "${PG_HBA_FILE}.backup"
fi

# Create new pg_hba.conf with expanded access rules
cat > "$PG_HBA_FILE" << 'EOF'
# PostgreSQL Client Authentication Configuration File
# =============================================================================
# SUJBOT Network Access Rules
# =============================================================================
# This file is auto-generated by 00-network-access.sh
#
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# =============================================================================

# Local connections (Unix domain socket)
local   all             all                                     trust

# IPv4 local connections
host    all             all             127.0.0.1/32            scram-sha-256

# IPv6 local connections
host    all             all             ::1/128                 scram-sha-256

# =============================================================================
# Docker Network Access
# =============================================================================
# Docker default bridge networks (172.17.0.0/16 and custom ranges)
host    all             all             172.16.0.0/12           scram-sha-256

# Docker user-defined networks and rootless Docker networks (10.x.x.x)
host    all             all             10.0.0.0/8              scram-sha-256

# =============================================================================
# Host Network Access (for rootless Docker)
# =============================================================================
# Allow connections from any IP (secured by password)
# This is needed for rootless Docker containers connecting via host IP
host    all             all             0.0.0.0/0               scram-sha-256
host    all             all             ::/0                    scram-sha-256

EOF

echo "pg_hba.conf configured successfully."
echo "Allowed networks:"
echo "  - Local socket (trust)"
echo "  - 127.0.0.1/32 (scram-sha-256)"
echo "  - 172.16.0.0/12 - Docker networks (scram-sha-256)"
echo "  - 10.0.0.0/8 - Docker networks (scram-sha-256)"
echo "  - 0.0.0.0/0 - All IPv4 (scram-sha-256) - for rootless Docker via host IP"
