-- ============================================================================
-- SUJBOT2 Authentication & Authorization Schema
-- ============================================================================
-- This script creates authentication and user management tables:
-- 1. Users table (authentication credentials)
-- 2. Conversations table (user-owned chat sessions)
-- 3. Messages table (conversation history)
--
-- Security features:
-- - Argon2 password hashing (handled in application layer)
-- - User ownership enforcement via foreign keys
-- - Automatic timestamp updates via triggers
-- ============================================================================

-- Ensure we're in the correct database
\c sujbot

-- ============================================================================
-- AUTH SCHEMA
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS auth;

-- ============================================================================
-- USERS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS auth.users (
    id SERIAL PRIMARY KEY,

    -- Credentials
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    -- Profile
    full_name VARCHAR(100),

    -- Status
    is_active BOOLEAN NOT NULL DEFAULT true,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_login_at TIMESTAMP WITH TIME ZONE,

    -- Agent variant preference
    agent_variant VARCHAR(20) DEFAULT 'premium' CHECK (agent_variant IN ('premium', 'local'))
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_users_email ON auth.users(email);
CREATE INDEX IF NOT EXISTS idx_users_active ON auth.users(is_active) WHERE is_active = true;

-- ============================================================================
-- CONVERSATIONS TABLE (User-Owned Chat Sessions)
-- ============================================================================

CREATE TABLE IF NOT EXISTS auth.conversations (
    id VARCHAR(36) PRIMARY KEY,  -- UUID format (generated by backend)
    user_id INTEGER NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Metadata
    title VARCHAR(500),

    -- Title generation state (prevents race conditions across workers)
    is_title_generating BOOLEAN NOT NULL DEFAULT false,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON auth.conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_updated_at ON auth.conversations(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_user_updated ON auth.conversations(user_id, updated_at DESC);

-- ============================================================================
-- MESSAGES TABLE (Conversation History)
-- ============================================================================

CREATE TABLE IF NOT EXISTS auth.messages (
    id SERIAL PRIMARY KEY,
    conversation_id VARCHAR(36) NOT NULL REFERENCES auth.conversations(id) ON DELETE CASCADE,

    -- Message content
    role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,

    -- Metadata (tool calls, agent progress, costs, etc.)
    metadata JSONB,

    -- Timestamp
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for fast retrieval
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON auth.messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON auth.messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_created ON auth.messages(conversation_id, created_at ASC);

-- ============================================================================
-- TRIGGERS FOR AUTO-UPDATE TIMESTAMPS
-- ============================================================================

-- Function to update updated_at column
CREATE OR REPLACE FUNCTION auth.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for users table
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION auth.update_updated_at_column();

-- Trigger for conversations table
CREATE TRIGGER update_conversations_updated_at
    BEFORE UPDATE ON auth.conversations
    FOR EACH ROW
    EXECUTE FUNCTION auth.update_updated_at_column();

-- ============================================================================
-- SEED DATA: Default Admin User
-- ============================================================================
-- Password: "ChangeThisPassword123!"
-- Hash: Will be replaced by migration script with real Argon2 hash

INSERT INTO auth.users (email, password_hash, full_name, is_active)
VALUES (
    'admin@sujbot.local',
    '$argon2id$v=19$m=65536,t=3,p=4$PLACEHOLDER',  -- Replace with real hash
    'System Administrator',
    true
)
ON CONFLICT (email) DO NOTHING;

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================

COMMENT ON SCHEMA auth IS 'Authentication and authorization tables';
COMMENT ON TABLE auth.users IS 'User accounts with Argon2 password hashes';
COMMENT ON TABLE auth.conversations IS 'User-owned chat conversations';
COMMENT ON TABLE auth.messages IS 'Message history for conversations';
COMMENT ON COLUMN auth.users.password_hash IS 'Argon2id hash (cost: m=65536, t=3, p=4)';
COMMENT ON COLUMN auth.messages.metadata IS 'JSONB: tool_calls, agent_progress, costs, etc.';
